#PBS -q regular
#PBS -l mppwidth=49152
#PBS -l walltime=04:00:00
#PBS -N output-all
#PBS -j oe
#PBS -V
#PBS -l gres=gscratch2

cd $PBS_O_WORKDIR
export OTHER=/global/homes/g/girving/otherlab/other

aprun -n 16384 -N 8 -j 2 $OTHER/install/edison-release/bin/endgame-mpi --ranks 16384 --threads 6 --save 18 --memory 7G --gather-limit 4 --line-limit 5 00000000 --dir data-all --randomize 17
# 2048 nodes

# 1 node = 24 cores (x2 with hyperthreading via -j 2), 64 GB RAM
