Import('env child external library')

external(env,'geode',default=1,required=1,libs=['geode'],headers=['geode/utility/config.h'])
external(env,'lzma',libs=['lzma'],headers=['lzma.h'],required=1)
external(env,'snappy',libs=['snappy'],headers=['snappy.h'],required=1)

child(env,'mpi')

generated = ['gen/%s'%f for f in 'tables.h tables.cpp'.split()]
env.Command(generated,'base/precompute.py','$SOURCE --prefix ${TARGET.dir}')

env = env.Clone(need_zlib=1,need_lzma=1,need_snappy=1)
env.Append(CPPPATH=['.'],CXXFLAGS='-Wno-invalid-offsetof')
library(env,'pentago_core',[],extra=['gen/tables.cpp'],skip=['mpi'])
