#PBS -q debug
#PBS -l mppwidth=96
#PBS -l walltime=00:20:00
#PBS -N output-small-ht
#PBS -j oe
#PBS -V
#PBS -l gres=gscratch2

cd $PBS_O_WORKDIR
export PENTAGO=/global/homes/g/girving/pentago

aprun -n 32 -N 8 -j 2 $PENTAGO/build/native/release/bin/endgame-mpi \
  --ranks 32 --threads 6 --save 0 --memory 3G --gather-limit 4 --line-limit 5 44444444 \
  --dir data-small --randomize 17
# 4 nodes

# 1 node = 24 cores (x2 with hyperthreading via -j 2), 64 GB RAM
