#!/usr/bin/env python3
"""gsutil compose, but handle more than 32 files"""

import optparse
import subprocess
import sys

# Command line options
usage = 'usage: %prog [-n] [srcs...] dst'
parser = optparse.OptionParser(usage)
parser.add_option('-n', '--nop', action='store_true', help='Print commands without executing')
options, args = parser.parse_args()
if len(args) < 2:
  parser.error('Need at least one src, then dst')
*srcs, dst = args

def run(cmd):
  print(' '.join(cmd))
  if not options.nop:
    subprocess.check_call(cmd)

while len(srcs) > 1:
  lo, hi = srcs[:32], srcs[32:]
  run(['gsutil', 'compose', *lo, dst]) 
  srcs = [dst] + hi
