#!/usr/bin/env python3
"""Estimate probability for use in beam.py"""

import numpy as np
import supertensors


def main():
  count = 100
  max_slice = 5

  sections = np.concatenate(supertensors.descendent_sections(max_slice))
  shapes = supertensors.section_shape(sections)
  shapes = np.asarray(shapes, dtype=np.uint64)
  total = np.uint64(256) * shapes.prod(axis=-1).sum()
  prob = count / total
  print(f'total {total}, prob {prob}')


if __name__ == '__main__':
  main()
