#!/usr/bin/env python3
"""Learning curve plotting"""

import pandas as pd
import pylab
import numpy as np
import re

def main():
  path = 'log-ev2-epochs.txt'
  data = []
  values_re = re.compile(r'(\w+) ([\d.-]+)(?:,\s+)')
  for line in open(path):
    data.append({k:float(v) for k, v in values_re.findall(line)})
  d = pd.DataFrame(data)
  print(d)
  #d.plot(x='step', y='loss', logx=True, logy=True)
  r = d.rolling(50).mean()
  r.plot(x='epochs', y='loss', loglog=True, grid=True)
  pylab.show()


if __name__ == '__main__':
  main()
