#!/usr/local/opt/python@3.8/bin/python3.8

"""
Commands:
  /usr/local/opt/python@3.7/bin/pip3.7 install jaxlib Cython
  /usr/local/opt/python@3.7/bin/python3.7 ./setup.py develop

  ./run-beam --region us-central1 --runner DataflowRunner --project naml-148801 \
    --temp_location gs://pentago-subsample/tmp --slice 5
"""

import argparse
import beam
import logging
import plan_beam
from apache_beam.options.pipeline_options import PipelineOptions
from apache_beam.options.pipeline_options import SetupOptions


def run(argv=None, save_main_session=True):
  # Parse arguments
  parser = argparse.ArgumentParser()
  parser.add_argument('--input', default='gs://pentago-us-central1', help='Input path')
  parser.add_argument('--output', default='gs://pentago-subsample', help='Output path')
  parser.add_argument('--slice', default=5, type=int, help='Slice to process')
  flags, pipeline_args = parser.parse_known_args(argv)
  options = PipelineOptions(pipeline_args)
  options.view_as(SetupOptions).save_main_session = save_main_session

  # Subsample!
  slice = flags.slice
  prob = plan_beam.PROBS[slice]
  shards = plan_beam.SHARDS[slice]
  beam.subsample(options=options, slices=[slice], index_path=flags.input, super_path=flags.input,
                 prob=prob, shards=shards, output_path=f'{flags.output}/subsample-{slice}')


if __name__ == '__main__':
  logging.getLogger().setLevel(logging.INFO)
  run()
