package(default_visibility = ["//visibility:public"])

filegroup(
    name = "slices",
    srcs = glob(["slice-*.pentago"]),
)

filegroup(
    name = "indexes",
    srcs = glob(["slice-*.pentago.index"]),
)

filegroup(
    name = "counts",
    srcs = glob(["counts-*.npy"]),
)
