#PBS -q regular
#PBS -l mppwidth=3072
#PBS -l walltime=01:00:00
#PBS -N output-medium
#PBS -j oe
#PBS -V
#PBS -l gres=gscratch2

cd $PBS_O_WORKDIR
aprun -n 512 -N 8 -j 2 $OTHER/install/edison-release/bin/endgame-mpi --ranks 512 --threads 6 --save 0 --memory 3G --gather-limit 4 --line-limit 5 44443333 --dir data-medium --randomize 17

# 1 node = 24 cores (x2 with hyperthreading via -j 2), 64 GB RAM
