#!/usr/bin/env python

from pentago import *

summary = None
for board in all_boards(1,8):
  win = meaningless(board,0)
  win_or_tie = win|meaningless(board,7)
  result = 'ltw'[win+win_or_tie]
  if 0:
    print 'board %d - %d%d\n%s\n'%(board,win,win_or_tie,show_board(board))
  s = show_board(board).replace('0',result)
  summary = ''.join(a if b=='_' else b for a,b in zip(summary,s)) if summary else s

print 'summary =\n%s'%summary
