Import('env library program')

env = env.Clone(use_mpi=1,use_zlib=1,use_lzma=1,use_snappy=1)
env.Append(CPPPATH=['..'],CXXFLAGS='-Wno-invalid-offsetof')
library(env,'pentago_mpi',['other_core','pentago_core'],skip=['main.cpp'])

env = env.Clone()
env.Append(LIBS=['pentago_mpi','pentago_core','other_core','m'])
program(env,'endgame-mpi','main.cpp')
