#!/usr/bin/env python
'''Upload website to rackspace'''

from __future__ import division,print_function,unicode_literals,absolute_import
import subprocess
import pyrax
import glob
import os

# Make sure everything is up to date
os.chdir(os.path.dirname(__file__))
subprocess.check_call(['make'])

# Authenticate
pyrax.set_credential_file(os.environ['HOME']+'/.pyrax.cfg')

# Upload
container = pyrax.cloudfiles.get_container('pentago-frontend')
files = dict((f.name,f) for f in container.get_objects())
for pattern in 'bundle.js *.html *.css *.png *.svg'.split():
  for name in glob.glob(pattern):
    if name not in ('nersc-logo.png',):
      if name in files and files[name].etag==pyrax.utils.get_checksum(name):
        continue
      print('upload %s'%name)
      obj = container.upload_file(name,name)
      obj.purge()
