#!/usr/bin/env python
'''Upload website to rackspace'''

from __future__ import division,print_function,unicode_literals,absolute_import
import subprocess
import glob
import os

# Make sure everything is up to date
os.chdir(os.path.dirname(__file__))
subprocess.check_call(['make'])

# Files to upload
files = []
for pattern in 'bundle.js *.html *.css *.png *.svg .htaccess'.split():
  for name in glob.glob(pattern):
    if name not in ('nersc-logo.png',):
      files.append(name)

def mediatemple():
  '''Deploy to mediatemple'''
  subprocess.call(['scp']+files+['mt:domains/perfect-pentago.net/html'])

# Deploy
mediatemple()
